  openapi: 3.0.0
  info:
    title: Experiment API(s)
    description: "- The Experiment API is used to create an experiment with user or device specifications. The Operations include create, get experiment  \n- The URL for Experiment API(S) is\
      \ `/data/v1/experiment`.
      - Postman collection for different testcases - [TestCases](https://www.getpostman.com/collections/a18a2d1dbc7504551638) "
    contact: {}
    version: '1.0'
  servers:
    - url: 'https://staging.open-sunbird.org/api/data/v1/experiement'
      variables: {}
  paths:
    /data/v1/experiement/create:
      post:
        tags:
          - V1
        summary: CreateExperiment
        description:  |-
          This API is used for create a new experiment based on particular user or device filters.  Respective user can create a experiment based on users filters(any user specific details like organisation, board, medium etc) or devices filters(state,first_access and district)
             - The endpoint for ** Experiment Create** is `/create
             - The fields marked with an asterisk (*) are mandatory. They cannot be null or empty.
        operationId: CreateExperiment
        requestBody:
          description: Represents the body and formdata parameters of the new experiment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateExperiment'
          required: true
        responses:
          '200':
            description: Success example for experiment create
            headers: {}
            content:
              application/json:
                schema:
                  oneOf:
                    - $ref: '#/components/schemas/CreateExperiment-200OK'
                    - $ref: '#/components/schemas/CreateExistedExperiment-200OK'
                examples:
                  New_Experiment:
                    summary: IF_NEW_EXPERIMENT
                    value: 
                      id: ekstep.analytics.experiement.create
                      ver: v1
                      ts: '2020-11-30T07:17:22.982+00:00  '
                      params:
                        resmsgid: 565b07a3a-d59f-47e6-b3d3-76cc5866411c
                        status: successful
                      responseCode: OK
                      result:
                        stats: {}
                        request: '#/components/schemas/Experiment-Request/example'
                        created_on: 1606818148268
                        last_updated: 1606818148268
                        status: SUBMITTED
                        status_msg: Experiment successfully submitted
                  Existing_Experiment:
                    summary: If_Experiment_Already_Exists
                    value: 
                      id: ekstep.analytics.experiement.create
                      ver: v1
                      ts: '2020-11-23 06:42:39:001+0000'
                      params:
                        resmsgid: 8c244093-e19d-4694-a4ba-342bc0f8b721
                        status: successful
                      responseCode: OK
                      result:
                       expResponse:
                         request: '#/components/schemas/Experiment-Request/example'
                         err: Failed
                         errorMsg: ExperimentId already exists.                    
        
          '400':
            description: Bad Request for create experiment
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CreateExperiment-400BadRequest'
                examples:
                  EmptyRequest:
                    summary: Request_Field_Missing
                    description: Response example when request is missing
                    value:
                      $ref: '#/components/schemas/CreateExperiment-400BadRequest/example'
                  RequiredRequestFieldsEmpty:
                    summary: Required Fields Missing in Request
                    description: Response example with all required fields
                    value:
                      id: ekstep.analytics.experiement.create
                      ver: v1
                      ts: '2020-11-23 06:42:39:001+0000'
                      params:
                        resmsgid: 8c244093-e19d-4694-a4ba-342bc0f8b721
                        status: failed
                        err: CLIENT_ERROR
                        errorMsg:
                          status: failed
                          request.expId: Created By should not be empty
                          request.name: Experiment Name should not be  empty
                          request.createdBy: Created By should not be empty
                      responseCode: CLIENT_ERROR
                      result: null
                  MissingDateFields:
                    summary: Missing_Date_Fields 
                    description: Response example with all required fields
                    value:
                      id: ekstep.analytics.experiement.create
                      ver: v1
                      ts: '2020-11-23 06:42:39:001+0000'
                      params:
                        resmsgid: 8c244093-e19d-4694-a4ba-342bc0f8b721
                        status: failed
                        err: CLIENT_ERROR
                        errorMsg:
                          status: failed
                          data.startDate: Experiment Start_Date should not be empty
                          data.endDate: Experiment End_Date should not be empty
                      responseCode: CLIENT_ERROR
                      result: null
                  InvalidDateFields:
                    summary: Invalid_Date_Fields 
                    description: Response example with all required fields
                    value:
                      id: ekstep.analytics.experiement.create
                      ver: v1
                      ts: '2020-11-23 06:42:39:001+0000'
                      params:
                        resmsgid: 8c244093-e19d-4694-a4ba-342bc0f8b721
                        status: failed
                        err: CLIENT_ERROR
                        errorMsg:
                          status: failed
                          data.endDate: End_Date should be greater than today's date.
                      responseCode: CLIENT_ERROR
                      result: null
                  StartEndDateValidation:
                    summary: Start_End_Date_Validation
                    description: Response example with all required fields
                    value:
                      id: ekstep.analytics.experiement.create
                      ver: v1
                      ts: '2020-11-23 06:42:39:001+0000'
                      params:
                        resmsgid: 8c244093-e19d-4694-a4ba-342bc0f8b721
                        status: failed
                        err: CLIENT_ERROR
                        errorMsg:
                          status: failed
                          data.startDate: Date range should not be -ve. Please check your start_date & end_date
                      responseCode: CLIENT_ERROR
                      result: null
          '500':
            description: Internal Server Error example for experiment create
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Experiment-500InternalServerError'
                example:
                  id: ekstep.analytics.experiment.create
                  ver: v1
                  ts: '2020-11-23 15:15:18:331+0000'
                  params:
                    resmsgid: null
                    msgid: null
                    err: INTERNAL_ERROR
                    status: SERVER_ERROR
                    errmsg: 'Process failed,please try again later.'
                  responseCode: SERVER_ERROR
                  result: {}
        deprecated: false
        security: []
    /data/v1/experiement/get/'{experiment-id}':
      get:
        tags:
          - V1
        summary: GetExperiment
        description:  |-
          This API is used for get particular experiment based on experiment id
             - The endpoint for ** Get Experiment** is `/{experiment-id}`
             - The fields marked with an asterisk (*) are mandatory. They cannot be null or empty.
        operationId: GetExperiment
        parameters:
          - name: experiment-id
            in: path
            description: ''
            required: true
            style: simple
            schema:
              type: string
        responses:
          '200':
            description: Success example for get particular experiment
            headers: {}
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/GetExperiment-200OK'
                examples:
                  Existing_Experiment:
                    summary: If_Experiment_Exists
                    value: 
                      id: ekstep.analytics.experiement.get
                      ver: v1
                      ts: '2020-11-23 06:42:39:001+0000'
                      params:
                        resmsgid: 8c244093-e19d-4694-a4ba-342bc0f8b721
                        status: successful
                      responseCode: OK
                      result:
                       stats: 
                        devicesMatched: 10000
                       request:
                        expId: D1234
                        name: DEVICE_EXP
                        createdBy: USER2
                        description: Experiment to redirect all users with device_state as Karnataka and first_access in range of october month to different app page
                        criteria:
                         type: device
                         filters: [
                           {
                             name: state,
                             operator: IN,
                             value: [KARNATAKA]
                           },
                           {
                             name: first_access,
                             operator:  RANGE,
                             value: { 
                               start: '2019-10-01',
                               end: '2019-10-30'
                             }
                           }
                          ]
                        data:
                          startDate: 2020-11-01
                          endDate: 2020-11-05
                          key: 24-32jewfjewout0sdf
                          client: app
                      created_date: 1602062500777
                      last_updated: 1602062542509
                      status: ACTIVE
                      status_msg: Experiment Mapped Sucessfully
                  Experiment_NOT_EXIST:
                    summary: If_Experiment_Doesnt_Exists
                    value: 
                      id: ekstep.analytics.experiment.get
                      ver: v1
                      ts: '2020-11-30T07:17:22.982+00:00  '
                      params:
                        err: OK
                        resmsgid: 25b07a3a-d59f-47e6-b3d3-76cc5866411c
                        status: failed
                        errmsg: no experiment available with the given experimentid
                      responseCode: OK
                      result: null
          '500':
            description: Internal Server Error example for batch create
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Experiment-500InternalServerError'
                example:
                  id: ekstep.analytics.experiment.submit
                  ver: v1
                  ts: '2020-11-23 15:15:18:331+0000'
                  params:
                    resmsgid: null
                    msgid: null
                    err: INTERNAL_ERROR
                    status: SERVER_ERROR
                    errmsg: 'Process failed,please try again later.'
                  responseCode: SERVER_ERROR
                  result: {}
        deprecated: false
  security:
    - bearerAuth: []      
    
  components:
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
    schemas:
      Params:
        title: Params
        required:
          - resmsgid
          - err
          - status
        type: object
        properties:
          resmsgid:
            type: string
            nullable: true
          err:
            type: string
          status:
            type: string
      ErrorParams:
        title: ErrorParams
        required:
          - resmsgid
          - err
          - status
          - errorMsg
        type: object
        properties:
          resmsgid:
            type: string
          err:
            type: string
          status:
            type: string 
          errorMsg:
            type: object
            properties:
              status:
                type: string
      CreateExperiment:
        title: CreateExperiment
        required:
          - request
        type: object
        properties:
          request:
            $ref: '#/components/schemas/Experiment-Request'
        example:
          request:
            expId: U1234
            name: USER_ORG
            description: Experiment to get users with orgname as sunbird to explore page 
            createdBy: User1
            criteria: 
              type: user
              filters:
                organisations.orgName: [sunbird]
            data:
              startDate: '2020-10-11'
              endDate: '2020-10-20'
              key: 'ASDSDFDK23SDFKJDK'
              client: app
              
      Experiment-Request:
        title: Experiment-Request
        required:
         - expId
         - name
         - createdBy
         - description
         - criteria
         - data
        type: object
        properties:
          expId:
           type: string
           description: Unique id for experiment
          name:
           type: string
           description: name of the experiment
          createdBy:
           type: string
           description: name of the user who created the experiment
          description:
           type: string
           description: Short description about the experiment
          criteria:
            $ref: '#/components/schemas/Criteria'
          data:
            $ref: '#/components/schemas/Data'
      Criteria:
       title: Criteria
       required:
         - type
         - filters
       properties:
         type:
           type: string
           description: Experiment type - either user or device
         filters:
           type: object
           description: Required filters based on user or device
       example:
         type: user
         filters: {
           organisations: sunbird
          }
      Data:
        title: Data
        required:
          - startDate
          - endDate
          - key
          - client
        properties:
          startDate:
            type: string
            description: Start date of the experiment
          endDate:
            type: string
            description: End date of the experiment
          key:
            type: string
            description: key of the experiment- For Example  url for portal or app key for app
          client:
            type: string
            description: experiment client - either app or portal
        example:
          startDate: "2020-10-11"
          endDate: "2020-10-19"
          key: '/org/profile'
          client: 'portal'
           
      CreateExperiment-200OK:
        title: CreateExperiment-200OK
        required:
          - id
          - ver
          - ts
          - params
          - responseCode
          - result
        type: object
        properties:
          id:
            type: string
          ver:
            type: string
          ts:
            type: string
          params:
            $ref: '#/components/schemas/Params'
          responseCode:
            type: string
          result:
            $ref: '#/components/schemas/Experiment-Response'
        example:
          id: ekstep.analytics.experiment.submit
          ver: v1
          ts: '2020-11-23 06:42:39:001+0000'
          params:
            resmsgid: 8c244093-e19d-4694-a4ba-342bc0f8b721
            status: successful
          responseCode: OK
          result:
            $ref: '#/components/schemas/Experiment-Response/example'
              
      Experiment-Response:
        title: Experiment-Response
        required:
          - stats
          - request
          - status
          - status_msg
        properties:
          stats:
            type: object
          request:
            $ref: '#/components/schemas/Experiment-Request'
          status:
            type: string
          status_msg:
            type: string
          created_on:
            type: string
          last_updated:
            type: string
        example:
          stats: {}
          request: '#/components/schemas/Experiment-Request/example'
          created_on: 1606818148268
          last_updated: 1606818148268
          status: SUBMITTED
          status_msg: Experiment successfully submitted
        
      CreateExistedExperiment-200OK:
        title: CreateExistedExperiment-200OK
        required:
          - id
          - ver
          - ts
          - params
          - responseCode
          - result
        type: object
        properties:
          id:
            type: string
          ver:
            type: string
          ts:
            type: string
          params:
            $ref: '#/components/schemas/Params'
          responseCode:
            type: string
          result:
            type: object
            properties: 
             expResponse:
                $ref: '#/components/schemas/Experiment-Response'
             err:
              type: string
             errorMsg:
              type: object
              properties:
                msg:
                  type: string    
        example:
          id: ekstep.analytics.experiement.create
          ver: v1
          ts: '2020-11-23 06:42:39:001+0000'
          params:
            resmsgid: 8c244093-e19d-4694-a4ba-342bc0f8b721
            status: successful
          responseCode: OK
          result:
           expResponse:
             request: '#/components/schemas/Experiment-Request/example'
             err: Failed
             errorMsg: ExperimentId already exists.
      CreateExperiment-400BadRequest:
        title: CreateExperiment-200OK
        required:
          - id
          - ver
          - ts
          - params
          - responseCode
          - result
        type: object
        properties:
          id:
            type: string
          ver:
            type: string
          ts:
            type: string
          params:
            $ref: '#/components/schemas/ErrorParams'
          responseCode:
            type: string
          result:
            type: string
        example:
          id: ekstep.analytics.experiement.create
          ver: v1
          ts: '2020-11-23 06:42:39:001+0000'
          params:
            resmsgid: 8c244093-e19d-4694-a4ba-342bc0f8b721
            status: failed
            err: CLIENT_ERROR
            errorMsg:
              status: failed
              request: Request should not be empty
          responseCode: CLIENT_ERROR
          result: null
      Experiment-500InternalServerError:
              title: Experiment-500InternalServerError
              required:
                - id
                - ver
                - ts
                - params
                - responseCode
                - result
              type: object
              properties:
                id:
                  type: string
                ver:
                  type: string
                ts:
                  type: string
                params:
                  $ref: '#/components/schemas/ErrorParams'
                responseCode:
                  type: string
                result:
                  type: object
              example:
                id: ekstep.analytics.experiement
                ver: v1
                ts: '2020-11-23 15:15:18:331+0000'
                params:
                  resmsgid: null
                  msgid: null
                  err: INTERNAL_ERROR
                  status: SERVER_ERROR
                  errmsg: 'Process failed,please try again later.'
                responseCode: SERVER_ERROR
                result: {}          
      GetExperiment-200OK:
        title: GetExperiment-200OK
        required:
          - id
          - ver
          - ts
          - params
          - responseCode
          - result
        type: object
        properties:
          id:
            type: string
          ver:
            type: string
          ts:
            type: string
          params:
            $ref: '#/components/schemas/Params'
          responseCode:
            type: string
          result:
            $ref: '#/components/schemas/Experiment-Request'
        example:
          id: ekstep.analytics.experiement.get
          ver: v1
          ts: '2020-11-23 06:42:39:001+0000'
          params:
            resmsgid: 8c244093-e19d-4694-a4ba-342bc0f8b721
            status: successful
          responseCode: OK
          result:
           stats: 
            devicesMatched: 10000
           request:
            expId: D1234
            name: DEVICE_EXP
            createdBy: USER2
            description: Experiment to redirect all users to different app page with device state as Karnataka and first access in range of october month 
            criteria:
             type: device
             filters: [
               {
                 name: state,
                 operator: IN,
                 value: [KARNATAKA]
               },
               {
                 name: first_access,
                 operator:  RANGE,
                 value: { 
                   start: '2019-10-01',
                   end: '2019-10-30'
                 }
               }
              ]
            data:
              startDate: 2020-11-01
              endDate: 2020-11-05
              key: 24-32jewfjewout0sdf
              client: app
          created_date: 1602062500777
          last_updated: 1602062542509
          status: ACTIVE
          status_msg: Experiment Mapped Sucessfully
  tags:
    - name: V1
      description: ''
